### List all messages

GET http://localhost:3000/messages


### Create a new Message

POST http://localhost:3000/messages
content-type: application/json

{
    "content":"Its Tested"
}

### Get Message
GET http://localhost:3000/messages/58